name: HuskHomesGUI
version: '${project.version}'
main: com.taus.huskhomes_gui.Application.Model.HuskHomesGUI
api-version: '1.20'
load: STARTUP
author: tauses

description: Custom Husk Homes GUI with customizable commands

aliases: [home, homes]
usage: "Usage: /homes"

commands:
  home:
    description: Opens GUI
    usage: "/home"
    permission: HHGUI.command.home
    permission-message: "You do not have permission to use this command."
    aliases: [homes]

permissions:
  HHhelp.command.help:
    description: "Allows use of /hhhelp"
    default: true

  HHGUI.command.home:
    description: "Allows use of /home"
    permission-message: "You do not have permission to use this command."

  HHGUI.slot.*:
    description: "Increases amount of homes you can have."
    permission-message: "You do not have permission to set more homes."
